"""Initial migration

Revision ID: f2ef5283d259
Revises: 
Create Date: 2026-05-31 20:50:10.467051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ef5283d259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    with op.batch_alter_table('complaint_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_categories_is_active'), ['is_active'], unique=False)

    op.create_table('system_settings',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.String(length=255), nullable=False),
    sa.Column('setting_type', sa.Enum('string', 'integer', 'decimal', 'boolean', name='system_setting_type'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('setting_key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('citizen', 'officer', 'admin', name='user_role'), nullable=False),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('security_answer_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('activity_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('wards',
    sa.Column('ward_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ward_name', sa.String(length=120), nullable=False),
    sa.Column('ward_code', sa.String(length=30), nullable=False),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.user_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ward_id'),
    sa.UniqueConstraint('ward_code')
    )
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wards_is_active'), ['is_active'], unique=False)

    op.create_table('complaints',
    sa.Column('complaint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_number', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Emergency', name='complaint_priority'), nullable=False),
    sa.Column('status', sa.Enum('Submitted', 'Assigned', 'In Progress', 'Resolved', 'Closed', name='complaint_status'), nullable=False),
    sa.Column('escalation_level', sa.Enum('Normal', 'Urgent', 'Critical', name='complaint_escalation_level'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('before_image_path', sa.String(length=255), nullable=True),
    sa.Column('after_image_path', sa.String(length=255), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('work_performed', sa.Text(), nullable=True),
    sa.Column('materials_used', sa.Text(), nullable=True),
    sa.Column('additional_remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.user_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['complaint_categories.category_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_assigned_officer_id'), ['assigned_officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_complaint_number'), ['complaint_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_complaints_escalation_level'), ['escalation_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_ward_id'), ['ward_id'], unique=False)

    op.create_table('complaint_updates',
    sa.Column('update_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Submitted', 'Assigned', 'In Progress', 'Resolved', 'Closed', name='complaint_update_status'), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('update_id')
    )
    with op.batch_alter_table('complaint_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_updates_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_updates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_updates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_updates_updated_by'), ['updated_by'], unique=False)

    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.UniqueConstraint('complaint_id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_rating'), ['rating'], unique=False)

    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('Complaint Submitted', 'Complaint Assigned', 'Status Updated', 'Complaint Resolved', 'Complaint Closed', 'System', name='notification_type'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_complaint_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_rating'))
        batch_op.drop_index(batch_op.f('ix_feedback_is_active'))
        batch_op.drop_index(batch_op.f('ix_feedback_citizen_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('complaint_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_updates_updated_by'))
        batch_op.drop_index(batch_op.f('ix_complaint_updates_status'))
        batch_op.drop_index(batch_op.f('ix_complaint_updates_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaint_updates_complaint_id'))

    op.drop_table('complaint_updates')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_ward_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_priority'))
        batch_op.drop_index(batch_op.f('ix_complaints_is_active'))
        batch_op.drop_index(batch_op.f('ix_complaints_escalation_level'))
        batch_op.drop_index(batch_op.f('ix_complaints_complaint_number'))
        batch_op.drop_index(batch_op.f('ix_complaints_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_category_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_assigned_officer_id'))

    op.drop_table('complaints')
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wards_is_active'))

    op.drop_table('wards')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_is_active'))

    op.drop_table('system_settings')
    with op.batch_alter_table('complaint_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_categories_is_active'))

    op.drop_table('complaint_categories')
    # ### end Alembic commands ###
